name: Trigger Target Workflow
on:
  push:
    branches: [moveit-humble]
permissions: read-all
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="Intel-Innersource" 
          repo_name="applications.robotics.safety.manipulation-failure-mitigation"  
          event_type="trigger-workflow" 
          service="moveit-humble"
          version="v0.0.1"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"